"""Typed contracts shared by the data layer, agents, graph and reports (docs/07)."""

from atrader.contracts.agents import (
    AgentReport,
    AnalystOutput,
    Challenge,
    Claim,
    ClaimDraft,
    DebateOutput,
    DebateTurn,
    JudgeOutput,
    JudgeVerdict,
    Reason,
    RiskOutput,
    RiskReview,
    Scenario,
    StrategyOutput,
    StrategyPlan,
    Synthesis,
    SynthesisOutput,
    Veto,
)
from atrader.contracts.common import (
    AgentStatus,
    Assessment,
    ClaimKind,
    ClaimStatus,
    Coverage,
    Horizon,
    Mode,
    RunStatus,
    StatementBasis,
)
from atrader.contracts.evidence import (
    Announcement,
    CoverageEntry,
    DerivedMetric,
    EvidenceItem,
    EvidenceKind,
    EvidencePack,
    FinancialFact,
    NewsItem,
    PriceBar,
    ShareholdingSnapshot,
    SourceRef,
)
from atrader.contracts.instruments import Listing
from atrader.contracts.run import ModelCall, ResearchReport, ResearchRequest

__all__ = [
    "AgentReport",
    "AgentStatus",
    "AnalystOutput",
    "Announcement",
    "Assessment",
    "Challenge",
    "Claim",
    "ClaimDraft",
    "ClaimKind",
    "ClaimStatus",
    "Coverage",
    "CoverageEntry",
    "DebateOutput",
    "DebateTurn",
    "DerivedMetric",
    "EvidenceItem",
    "EvidenceKind",
    "EvidencePack",
    "FinancialFact",
    "Horizon",
    "JudgeOutput",
    "JudgeVerdict",
    "Listing",
    "Mode",
    "ModelCall",
    "NewsItem",
    "PriceBar",
    "Reason",
    "ResearchReport",
    "ResearchRequest",
    "RiskOutput",
    "RiskReview",
    "RunStatus",
    "Scenario",
    "ShareholdingSnapshot",
    "SourceRef",
    "StatementBasis",
    "StrategyOutput",
    "StrategyPlan",
    "Synthesis",
    "SynthesisOutput",
    "Veto",
]
