/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Instruments */
        get: operations["search_instruments_v1_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instruments/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bars */
        get: operations["get_bars_v1_instruments__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_v1_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_v1_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{report_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_v1_reports__report_id__evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_v1_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-sent events: `status`, `progress`, `node` and a final `end`. A client that
         *     reconnects with `Last-Event-ID` (or `?after=`, for a fresh `EventSource`) receives
         *     only what it missed.
         */
        get: operations["run_events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add To Watchlist */
        put: operations["add_to_watchlist_v1_watchlist__symbol__put"];
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_v1_watchlist__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Adjustment */
        Adjustment: {
            /**
             * Session
             * Format: date
             */
            session: string;
            /** Factor */
            factor: number;
        };
        /** AgentReport */
        AgentReport: {
            /** Agent */
            agent: string;
            /** Roles */
            roles: string[];
            status: components["schemas"]["AgentStatus"];
            stance: components["schemas"]["Assessment"] | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Gaps */
            gaps: string[];
            /** Score Adjustments */
            score_adjustments: components["schemas"]["ScoreAdjustment"][];
            /** Events */
            events: components["schemas"]["EventRating"][];
            /** Model Call Ids */
            model_call_ids: string[];
            /**
             * Prompt Version
             * @default
             */
            prompt_version: string;
            /** Error */
            error: string | null;
        };
        /**
         * AgentStatus
         * @enum {string}
         */
        AgentStatus: "completed" | "partial" | "abstained" | "skipped" | "failed";
        /** Announcement */
        Announcement: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /** Isin */
            isin: string | null;
            /** Symbol */
            symbol: string;
            /** Category */
            category: string;
            /** Summary */
            summary: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Attachment Url */
            attachment_url: string | null;
            source: components["schemas"]["SourceRef"];
        };
        /**
         * Assessment
         * @enum {string}
         */
        Assessment: "supportive" | "mixed" | "adverse" | "insufficient_evidence";
        /** Bar */
        Bar: {
            /**
             * Session
             * Format: date
             */
            session: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /**
             * Delivery Pct
             * @description Delivery share of traded quantity, %
             */
            delivery_pct: number | null;
        };
        /** BarsOut */
        BarsOut: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Isin */
            isin: string;
            /** Adjusted */
            adjusted: boolean;
            /** Adjustments */
            adjustments: components["schemas"]["Adjustment"][];
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /**
             * Averages
             * @description Simple moving averages (sma20, sma50, sma200), one value per bar
             */
            averages: {
                [key: string]: (number | null)[];
            };
        };
        /** Challenge */
        Challenge: {
            /**
             * Target Claim Id
             * @description The claim ID you dispute, e.g. C-bull-1-2.
             */
            target_claim_id: string;
            /**
             * Dispute
             * @enum {string}
             */
            dispute: "fact" | "assumption" | "mechanism" | "valuation";
            /** Argument */
            argument: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** Claim */
        Claim: {
            /**
             * Statement
             * @description One specific, checkable sentence.
             */
            statement: string;
            /** @description fact = reported figure or event; calculation = derived number; interpretation = reasoned judgement; scenario = conditional possibility. */
            kind: components["schemas"]["ClaimKind"];
            /**
             * Evidence Ids
             * @description IDs from the evidence pack (e.g. F3, M12, A2). Facts and calculations need at least one. Never invent an ID.
             */
            evidence_ids: string[];
            /** Assumptions */
            assumptions: string[];
            /** Claim Id */
            claim_id: string;
            /** Agent */
            agent: string;
            status: components["schemas"]["ClaimStatus"];
            /** Issues */
            issues: string[];
        };
        /**
         * ClaimKind
         * @enum {string}
         */
        ClaimKind: "fact" | "calculation" | "interpretation" | "scenario";
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "supported" | "needs_review" | "unsupported";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /**
         * Coverage
         * @description Availability of one source category for a run (docs/05, "Freshness and coverage").
         * @enum {string}
         */
        Coverage: "available" | "partial" | "stale" | "missing" | "access_blocked" | "not_applicable" | "not_requested";
        /** CoverageEntry */
        CoverageEntry: {
            /** Category */
            category: string;
            status: components["schemas"]["Coverage"];
            /**
             * Detail
             * @default
             */
            detail: string;
            /** As Of */
            as_of: string | null;
        };
        /** DebateTurn */
        DebateTurn: {
            /** Turn Index */
            turn_index: number;
            /**
             * Side
             * @enum {string}
             */
            side: "bull" | "bear";
            /**
             * Phase
             * @enum {string}
             */
            phase: "opening" | "rebuttal";
            status: components["schemas"]["AgentStatus"];
            /**
             * Thesis
             * @default
             */
            thesis: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Challenges */
            challenges: components["schemas"]["Challenge"][];
            /** Falsifiers */
            falsifiers: string[];
            /** Unresolved Questions */
            unresolved_questions: string[];
            /** Model Call Ids */
            model_call_ids: string[];
            /**
             * Prompt Version
             * @default
             */
            prompt_version: string;
            /** Error */
            error: string | null;
        };
        /**
         * DerivedMetric
         * @description A value computed in Python from stored inputs. Reproducible from `inputs`.
         */
        DerivedMetric: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Value */
            value: number | null;
            /** Unit */
            unit: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Formula */
            formula: string;
            /**
             * Formula Version
             * @default 1
             */
            formula_version: string;
            /**
             * Inputs
             * @default []
             */
            inputs: string[];
            /** Detail */
            detail: string | null;
            /**
             * Quality Flags
             * @default []
             */
            quality_flags: string[];
            /**
             * Category
             * @default fundamental
             * @enum {string}
             */
            category: "fundamental" | "valuation" | "technical" | "liquidity" | "pattern" | "market" | "flow" | "level" | "institutional";
        };
        /** EventRating */
        EventRating: {
            /**
             * Event
             * @description One sentence naming the event.
             */
            event: string;
            /**
             * Impact
             * @description -2 clearly negative, -1, 0 neutral, +1, +2 clearly positive for the company's prospects.
             */
            impact: number;
            /**
             * Materiality
             * @description How much the event matters relative to the company's size.
             * @enum {string}
             */
            materiality: "low" | "medium" | "high";
            /**
             * Evidence Ids
             * @description A or N IDs.
             */
            evidence_ids: string[];
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "facts" | "metrics" | "announcements" | "shareholding" | "news" | "institutional_activity";
            /** Item */
            item: {
                [key: string]: unknown;
            };
        };
        /**
         * EvidencePack
         * @description Everything a run may cite, frozen before interpretation starts.
         */
        EvidencePack: {
            listing: components["schemas"]["Listing"];
            /**
             * Cutoff
             * Format: date
             */
            cutoff: string;
            /**
             * Built At
             * Format: date-time
             */
            built_at: string;
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["FinancialFact"][];
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["DerivedMetric"][];
            /**
             * Announcements
             * @default []
             */
            announcements: components["schemas"]["Announcement"][];
            /**
             * Shareholding
             * @default []
             */
            shareholding: components["schemas"]["ShareholdingSnapshot"][];
            /**
             * News
             * @default []
             */
            news: components["schemas"]["NewsItem"][];
            /**
             * Institutional Activity
             * @default []
             */
            institutional_activity: components["schemas"]["InstitutionalActivity"][];
            /**
             * Indices
             * @default []
             */
            indices: components["schemas"]["IndexSeries"][];
            /** Industry */
            industry: string | null;
            /**
             * Coverage
             * @default []
             */
            coverage: components["schemas"]["CoverageEntry"][];
        };
        /**
         * Factor
         * @description One rule's contribution to a pillar score, with the evidence it read.
         *
         *     Rules in the same group read the same underlying move, so a group's total is
         *     capped; the cap shows up as its own factor (`kind="cap"`) so the factors still add
         *     up to the score.
         */
        Factor: {
            /** Label */
            label: string;
            /** Points */
            points: number;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Group */
            group: string | null;
            /**
             * Kind
             * @default rule
             * @enum {string}
             */
            kind: "rule" | "cap";
        };
        /**
         * FinancialFact
         * @description A reported figure, stored in base units (INR, not crore) with its reporting context.
         */
        FinancialFact: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /** Isin */
            isin: string;
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Value */
            value: string | null;
            /** Unit */
            unit: string;
            /** Period Start */
            period_start: string | null;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Duration
             * @enum {string}
             */
            duration: "quarter" | "half_year" | "nine_months" | "annual" | "instant" | "other";
            basis: components["schemas"]["StatementBasis"];
            /** Audited */
            audited: boolean | null;
            /** Rounding */
            rounding: string | null;
            /**
             * Filed At
             * Format: date-time
             */
            filed_at: string;
            source: components["schemas"]["SourceRef"];
            /** Missing Reason */
            missing_reason: string | null;
            /** Revision Note */
            revision_note: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Horizon
         * @description The three outlook horizons every report scores.
         * @enum {string}
         */
        Horizon: "1m" | "6m" | "2y";
        /** HorizonNote */
        HorizonNote: {
            horizon: components["schemas"]["Horizon"];
            /**
             * Adjustment
             * @description Between -5 and +5 points on the draft score, only where the debate or risk reviews show it misses something material. Usually 0.
             * @default 0
             */
            adjustment: number;
            /**
             * Adjustment Reason
             * @default
             */
            adjustment_reason: string;
            /**
             * Drivers
             * @description What most drives this horizon's view, one short line each.
             */
            drivers: string[];
            /**
             * Up If
             * @description Observable events that would raise the signal.
             */
            up_if: string[];
            /**
             * Down If
             * @description Observable events that would lower the signal.
             */
            down_if: string[];
        };
        /** HorizonSummary */
        HorizonSummary: {
            /** Horizon */
            horizon: string;
            /** Score */
            score: number | null;
            signal: components["schemas"]["Signal"];
            confidence: components["schemas"]["Confidence"];
        };
        /** HorizonView */
        HorizonView: {
            horizon: components["schemas"]["Horizon"];
            /** Score */
            score: number | null;
            signal: components["schemas"]["Signal"];
            confidence: components["schemas"]["Confidence"];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Weight Covered */
            weight_covered: number;
            driven_by: components["schemas"]["Pillar"] | null;
            /**
             * Manager Adjustment
             * @default 0
             */
            manager_adjustment: number;
            /** Manager Reason */
            manager_reason: string | null;
            /** Capped By */
            capped_by: string[];
            price_range: components["schemas"]["PriceRange"] | null;
            /** Drivers */
            drivers: string[];
            /** Up If */
            up_if: string[];
            /** Down If */
            down_if: string[];
        };
        /**
         * IndexSeries
         * @description An NSE index the stock is compared with: daily closes and its published P/E.
         */
        IndexSeries: {
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "benchmark" | "sector";
            /** Pe */
            pe: number | null;
            /** Pe As Of */
            pe_as_of: string | null;
        };
        /**
         * InstitutionalActivity
         * @description One market-wide cash observation. Availability is when we first observed this version.
         */
        InstitutionalActivity: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /**
             * Session
             * Format: date
             */
            session: string;
            /**
             * Participant
             * @enum {string}
             */
            participant: "FPI" | "DII";
            /**
             * Scope
             * @enum {string}
             */
            scope: "nse" | "combined";
            /**
             * Basis
             * @default provisional
             * @enum {string}
             */
            basis: "provisional" | "confirmed";
            /** Purchases Inr */
            purchases_inr: number;
            /** Sales Inr */
            sales_inr: number;
            /** Net Inr */
            net_inr: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            source: components["schemas"]["SourceRef"];
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Isin */
            isin: string;
        };
        /**
         * Level
         * @description A price the stock turned from or traded heavily at before. Not a target.
         */
        Level: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "resistance" | "support" | "average" | "vwap" | "volume" | "range";
            /** Label */
            label: string;
            /** Price */
            price: number;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Evidence Id */
            evidence_id: string;
        };
        /** Listing */
        Listing: {
            /** Symbol */
            symbol: string;
            /**
             * Exchange
             * @default NSE
             * @enum {string}
             */
            exchange: "NSE" | "BSE";
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /**
             * Series
             * @default EQ
             */
            series: string;
            /** Listed On */
            listed_on: string | null;
            /** Face Value */
            face_value: number | null;
            /**
             * Source
             * @default nse.equity_list
             */
            source: string;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "data_only" | "compact" | "full";
        /** ModelCall */
        ModelCall: {
            /** Call Id */
            call_id: string;
            /** Run Id */
            run_id: string;
            /** Node */
            node: string;
            /** Attempt */
            attempt: number;
            /** Requested Model */
            requested_model: string;
            /** Served Model */
            served_model: string | null;
            /** Provider */
            provider: string | null;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Completion Tokens */
            completion_tokens: number | null;
            /** Cost */
            cost: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "invalid_output" | "error" | "blocked";
            /** Error */
            error: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ModelStatus */
        ModelStatus: {
            /** Api Key Set */
            api_key_set: boolean;
            /** Quick */
            quick: string;
            /** Deep */
            deep: string;
        };
        /** NewsItem */
        NewsItem: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Domain */
            domain: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Language */
            language: string | null;
            source: components["schemas"]["SourceRef"];
        };
        /**
         * Pillar
         * @description One scored area of the research. Each belongs to the analyst that reviews it.
         * @enum {string}
         */
        Pillar: "technical" | "growth_quality" | "valuation" | "news";
        /**
         * PillarScore
         * @description A 0-100 score for one area. Every area starts at 50 (no lean either way).
         */
        PillarScore: {
            pillar: components["schemas"]["Pillar"];
            /** Score */
            score: number | null;
            /** Base */
            base: number | null;
            /**
             * Adjustment
             * @default 0
             */
            adjustment: number;
            /** Adjustment Reason */
            adjustment_reason: string | null;
            /** Adjustment Evidence */
            adjustment_evidence: string[];
            /** Factors */
            factors: components["schemas"]["Factor"][];
            /** @default low */
            confidence: components["schemas"]["Confidence"];
            /** Note */
            note: string | null;
        };
        /**
         * PriceBar
         * @description One end-of-day bar. Provider and adjustment basis are part of its identity.
         */
        PriceBar: {
            /**
             * Session
             * Format: date
             */
            session: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Prev Close */
            prev_close: number | null;
            /** Volume */
            volume: number;
            /** Turnover Inr */
            turnover_inr: number | null;
            /** Trades */
            trades: number | null;
            /** Delivery Pct */
            delivery_pct: number | null;
            /**
             * Provider
             * @default nse.bhavcopy
             */
            provider: string;
            /**
             * Adjustment
             * @default unadjusted
             * @enum {string}
             */
            adjustment: "unadjusted" | "split_bonus_adjusted";
        };
        /** PriceLevels */
        PriceLevels: {
            /** Close */
            close: number;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            support_break: components["schemas"]["Level"] | null;
            /** Flips */
            flips: components["schemas"]["SignalFlip"][];
        };
        /**
         * PriceRange
         * @description How far the price has typically moved, or what stated scenarios imply. Not a
         *     forecast.
         */
        PriceRange: {
            /**
             * Method
             * @enum {string}
             */
            method: "volatility" | "scenario";
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Base */
            base: number | null;
            confidence: components["schemas"]["Confidence"];
            /** Detail */
            detail: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** Quote */
        Quote: {
            /** Close */
            close: number;
            /**
             * Session
             * Format: date
             */
            session: string;
            /** Change Pct */
            change_pct: number | null;
        };
        /** Reason */
        Reason: {
            /** Statement */
            statement: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** ReportSummary */
        ReportSummary: {
            /** Report Id */
            report_id: string;
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string | null;
            /** Cutoff */
            cutoff: string | null;
            mode: components["schemas"]["Mode"];
            status: components["schemas"]["RunStatus"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Model Adjusted */
            model_adjusted: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Close */
            close: number | null;
            /** Horizons */
            horizons: components["schemas"]["HorizonSummary"][];
        };
        /** ResearchReport */
        ResearchReport: {
            /** Report Id */
            report_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            status: components["schemas"]["RunStatus"];
            request: components["schemas"]["ResearchRequest"];
            pack: components["schemas"]["EvidencePack"] | null;
            scorecard: components["schemas"]["Scorecard"] | null;
            /** Vetoes */
            vetoes: components["schemas"]["Veto"][];
            /** Coverage */
            coverage: components["schemas"]["CoverageEntry"][];
            /** Analyst Reports */
            analyst_reports: components["schemas"]["AgentReport"][];
            /** Debate */
            debate: components["schemas"]["DebateTurn"][];
            /** Risk Reviews */
            risk_reviews: components["schemas"]["RiskReview"][];
            final_synthesis: components["schemas"]["Synthesis"] | null;
            /** Model Calls */
            model_calls: components["schemas"]["ModelCall"][];
            /** Notes */
            notes: string[];
            /** Limitations */
            limitations: string[];
        };
        /** ResearchRequest */
        ResearchRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Exchange
             * @default NSE
             * @constant
             */
            exchange: "NSE";
            /** @default compact */
            mode: components["schemas"]["Mode"];
            /**
             * Cutoff
             * @description Knowledge cutoff; None means the latest completed data.
             */
            cutoff: string | null;
        };
        /** RiskReview */
        RiskReview: {
            /**
             * Verdict
             * @description Are the draft scores too optimistic (too_high), fair, or too pessimistic (too_low) given the risks you see?
             * @enum {string}
             */
            verdict: "too_high" | "fair" | "too_low";
            /** Objections */
            objections: string[];
            /**
             * Constraints
             * @description Conditions that should hold before relying on the signal.
             */
            constraints: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Rationale */
            rationale: string;
            /**
             * Perspective
             * @enum {string}
             */
            perspective: "aggressive" | "conservative" | "neutral";
            /** @default completed */
            status: components["schemas"]["AgentStatus"];
            /** Model Call Ids */
            model_call_ids: string[];
            /**
             * Prompt Version
             * @default
             */
            prompt_version: string;
        };
        /** RunBody */
        RunBody: {
            /**
             * Symbol
             * @description NSE symbol or ISIN
             */
            symbol: string;
            /** @default compact */
            mode: components["schemas"]["Mode"];
            /** Cutoff */
            cutoff?: string | null;
            /**
             * Dry Run
             * @description Placeholder model output; no requests
             * @default false
             */
            dry_run: boolean;
        };
        /** RunOut */
        RunOut: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Detail */
            detail: string | null;
            request: components["schemas"]["RunRequestOut"];
            /** Dry Run */
            dry_run: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Report Id */
            report_id: string | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["StageOut"][];
            /**
             * Last Event Id
             * @default 0
             */
            last_event_id: number;
        };
        /** RunRequestOut */
        RunRequestOut: {
            /** Symbol */
            symbol: string;
            mode: components["schemas"]["Mode"];
            /** Cutoff */
            cutoff: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "paused_quota" | "cancelled" | "completed" | "partial" | "failed";
        /** ScoreAdjustment */
        ScoreAdjustment: {
            /** @description The code-computed score you are adjusting (your own). */
            pillar: components["schemas"]["Pillar"];
            /**
             * Points
             * @description Between -15 and +15. Code clamps anything outside.
             */
            points: number;
            /**
             * Reason
             * @description One sentence: what the scoring rules missed.
             */
            reason: string;
            /**
             * Evidence Ids
             * @description At least one ID.
             */
            evidence_ids: string[];
        };
        /** Scorecard */
        Scorecard: {
            /** Version */
            version: string;
            /** Pillars */
            pillars: components["schemas"]["PillarScore"][];
            /** Horizons */
            horizons: components["schemas"]["HorizonView"][];
            /** Model Adjusted */
            model_adjusted: boolean;
            levels: components["schemas"]["PriceLevels"] | null;
        };
        /** ShareholdingSnapshot */
        ShareholdingSnapshot: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Promoter Pct */
            promoter_pct: number | null;
            /** Public Pct */
            public_pct: number | null;
            /** Employee Trust Pct */
            employee_trust_pct: number | null;
            /** Published At */
            published_at: string | null;
            /** Remarks */
            remarks: string | null;
            source: components["schemas"]["SourceRef"];
        };
        /**
         * Signal
         * @enum {string}
         */
        Signal: "strong_bullish" | "bullish" | "neutral" | "bearish" | "strong_bearish" | "insufficient_data";
        /**
         * SignalFlip
         * @description The nearest next-session close that would change a horizon's signal, with
         *     every other input held as it is.
         */
        SignalFlip: {
            horizon: components["schemas"]["Horizon"];
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
            /** Price */
            price: number | null;
            signal: components["schemas"]["Signal"] | null;
            /** Searched Pct */
            searched_pct: number;
        };
        /**
         * SourceRef
         * @description Where a piece of evidence came from and when it became public.
         */
        SourceRef: {
            /** Provider */
            provider: string;
            /** Url */
            url: string | null;
            /** Published At */
            published_at: string | null;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Content Hash */
            content_hash: string | null;
        };
        /** StageOut */
        StageOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Nodes */
            nodes: string[];
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "partial" | "done" | "skipped" | "error";
        };
        /**
         * StatementBasis
         * @enum {string}
         */
        StatementBasis: "standalone" | "consolidated";
        /** StatusOut */
        StatusOut: {
            /** Version */
            version: string;
            /** Latest Session */
            latest_session: string | null;
            model: components["schemas"]["ModelStatus"];
            /** Active Runs */
            active_runs: number;
            usage: components["schemas"]["Usage"];
        };
        /** Synthesis */
        Synthesis: {
            /**
             * Summary
             * @description Two or three plain sentences a non-expert understands.
             */
            summary: string;
            /** Pros */
            pros: components["schemas"]["Reason"][];
            /** Cons */
            cons: components["schemas"]["Reason"][];
            /**
             * Horizons
             * @description One note each for 1m, 6m and 2y.
             */
            horizons: components["schemas"]["HorizonNote"][];
            /** Unresolved */
            unresolved: string[];
            /**
             * Thesis Tests
             * @description Three decisive assumptions with falsifiers when supported; missing ones belong in unresolved. Never invent a disclosed next event.
             */
            thesis_tests: components["schemas"]["ThesisTest"][];
            /** @default completed */
            status: components["schemas"]["AgentStatus"];
            /** Dropped Reasons */
            dropped_reasons: string[];
            /** Model Call Ids */
            model_call_ids: string[];
            /**
             * Prompt Version
             * @default
             */
            prompt_version: string;
        };
        /**
         * ThesisTest
         * @description A thesis assumption paired with an observable falsifier and a disclosed next event.
         */
        ThesisTest: {
            /** Assumption */
            assumption: string;
            /**
             * Evidence Ids
             * @description Evidence for the assumption.
             */
            evidence_ids: string[];
            /**
             * Invalidated By
             * @description Observable condition that would disprove it.
             */
            invalidated_by: string;
            /**
             * Next Event
             * @description Next disclosed event; null when unknown.
             */
            next_event: string | null;
            /** Next Event Date */
            next_event_date: string | null;
            /**
             * Next Event Evidence Ids
             * @description Official disclosure A IDs supporting the next event.
             */
            next_event_evidence_ids: string[];
        };
        /** Usage */
        Usage: {
            /** Used Today */
            used_today: number;
            /** Usable */
            usable: number;
            /** Remaining */
            remaining: number;
            /** Daily Limit */
            daily_limit: number;
            /** Reserve */
            reserve: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Veto
         * @description A code-enforced constraint. `block` withholds every signal; `cap` holds each
         *     horizon's score at Neutral or below. A persuasive narrative cannot lift either.
         */
        Veto: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "block" | "cap" | "note";
            /** Message */
            message: string;
        };
        /** WatchlistItem */
        WatchlistItem: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            quote: components["schemas"]["Quote"] | null;
            latest_report: components["schemas"]["ReportSummary"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOut"];
                };
            };
        };
    };
    get_usage_v1_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
        };
    };
    search_instruments_v1_instruments_get: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bars_v1_instruments__symbol__bars_get: {
        parameters: {
            query?: {
                sessions?: number;
                until?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_v1_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"][];
                };
            };
        };
    };
    list_reports_v1_reports_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_v1_reports__report_id__evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_v1_reports__report_id__export_get: {
        parameters: {
            query?: {
                format?: "card" | "details" | "json";
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_v1_watchlist__symbol__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_v1_watchlist__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
